spring.application.name=restaurante

spring.datasource.url=jdbc:mysql://localhost:3306/gestion_restaurante
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=javiiriveero7@gmail.com
spring.mail.password=${MAIL_PASSWORD:vfnp hxua pcil fdzi}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.base-url=http://localhost:4200

spring.mail.properties.mail.debug=true

jwt.secret=${JWT_SECRET:94f1c1f5139a04467d589d81d2df6df0164c062835db6f9f30b91eb08149ba55}
jwt.expiration=86400000

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}
app.precio-medio-comensal=${PRECIO_MEDIO:25}
